#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#



library(shiny)
library(ggplot2)
library(mosaic)

UIcharSetEnglish = list(headTitle = "Social Relationship Network Graph",
                        name = "By Name",
                        date = "By Date",
                        vote = "By Vote",
                        vcolor = "Color for Persons",
                        ecolor = "Color for Lines",
                        vSize = "Size of Target Node",
                        eLWD = "Size for Lines",
                        vfcolor = "Color of Target Node",
                        efcolor = "Color for Labels of Lines")

UIcharSet = UIcharSetEnglish
colorSet <- c("grey","skyblue","turquoise","tomato","tan","slateblue",
              "wheat","sienna","black")


shinyUI(fluidPage(
    
    

    # Application title
    titlePanel("Social Network Structure"),

    sidebarLayout(
        
        sidebarPanel(
            checkboxInput("Date",UIcharSet$date,T),
            checkboxInput("Name",UIcharSet$name,F),
            checkboxInput("Vote",UIcharSet$vote,F),
            selectInput(inputId = "bins",
                        label = "Target Names",
                        choices = c("BDD","Bilby","Darkwind","INeverCry","Jason Quinn","Legoktm","Lord Roem","Mattythewhite","Miniapolis","Mkdw",
                                    "Nthep","Ocaasi","Paulmcdonald","RockMagnetist","Secret","Shirt58","Tokyogirl79","West.andrew.g","Ymblanter","angelo1345",
                                    "AppleJack-7","Banaticus","Binksternet","Carrite","DCI2026","Dirtlawyer1","Hahc21","Jasper Deng","KumiokoCleanStart","Piotrus",
                                    "Pjoef","Satellizer","Theopolisme","TortoiseWrath","Vacation9","Bagumba","Basalisk","Bbb23","Berean Hunter","Bgwhite",
                                    "Crisco 1492","De728631","Dennis Brown","Dpmuk","Ekabhishek","Fayenatic london","GiantSnowman","Harrias","ItsZippy","Jenks24",
                                    "KTC","Mark Arsten","MikeLynch","Monty845","Mr. Stradivarius","SarahStierch","Scottywong","Sergecross73","TommyBoy","Writ Keeper",
                                    "Yngvadottir","Yunshui","Zagalejo","Œ£","987li","Anbu121","Apteva","AutomaticStrikeout","Avicennasis","Baseballrocks538",
                                    "Bens dream","Calabe1992","Central Data Bank","Dannyboy1209","Darkness Shines","Deathlibrarian","Dipankan001","Distributor108","Farrtj","Faustus37",
                                    "Figureskatingfan","Floydian","GabeMc","Gigs","GSorby","Hghyux","History2007","James1011R","Jeff G.","JordanKyser22",
                                    "Kamek98","Karthikndr","Ktr101","Kumioko","LuK3","Mabdul","Mapalazoo","Marcus Qwertyus","Master&Expert","Mlpearc",
                                    "MONGO","Mr little irish","My76Strat","Northamerica1000","Penyulap","PerryThePlatypusFan","Pol430","PumpkinSky","Purplebackpack89","QuiteUnusual",
                                    "Raghusri","Rcsprinter123","ronjohn","Ryan Vesey","Sk8terguy27","SpeakFree","Sven Manguard","Swinquest","SwisterTwister","The Determinator",
                                    "TheAustinMan","TucsonDavid","Vibhijain","WinEuro","XyphynX9","28bytes","5 albert square","Acdixon","Anomie","Bahamut0013",
                                    "Boing! said Zebedee","Catfish Jim and the soapdish","CharlieEchoTango","DeltaQuad","Drmies","ErikHaugen","ErrantX","F√¶","Feezo","Fluffernutter",
                                    "GB fan","Gfoley4","Gimme danger","Gonzonoir","Guerillero","HJ Mitchell","Ironholds","JaGa","January","Jimp",
                                    "Ks0stm","Kudpung","Lear's Fool","MichaelQSchmidt","Neelix","Peridon","Ponyo","Qwyrxian","Rami R","Rannph√°irt√≠ anaithnid",
                                    "Reaper Eternal","Redrose64","RHM22","Richwales","Sadads","Salvio giuliano","SarekOfVulcan","Slon02","Smartse","Swarm",
                                    "The Blade of the Northern Lights","The Bushranger","Tom Morris","TParis","Tyrol5","Valfontis","Worm That Turned","A520","A930913","Ancient Apparition",
                                    "Andrew J Powers","Ankitbhatt","Ankitkool1988","Ant682","Armbrust","AwesomeSponge","Breawycker","Buggie111","BuickCenturyDriver","BusterD",
                                    "Cjc811","Coolguy22468","Core2012","Cprice1000","Ctjf83","Curtis23","CWH","Dayewalker","Dudemanfellabra","Dusti",
                                    "Dylan620","E2eamon","Ebikeguy","Eduemoni","Giftiger wunsch","Glane23","Guoguo12","GutiLucian02","Hallows AG","HangingCurve",
                                    "Hazard-SJ","Inka 888","J√©sk√© Couriano","Jsfouche","Katharineamy","Ke5crz","Kylekieran","Latish redone","Logan","MacMed",
                                    "Methecooldude","Moxy","N419BH","N5iln","Neutralhomer","NickPenguin","NYMets2000","Nyswimmer","RadioFan","Reenem",
                                    "Rehman","Richardcavell","RobertMfromLI","SilverSoul91911","Snakenath","Snottywong","Spongefrog","Staffwaterboy","Steven Zhang","SunCountryGuy01",
                                    "Tarheel95","TedPavlic","Timl2k4","Ttonyb1","VegetaSaiyan","Wcreed88","Who Am I Why Am I Here","WikiCopter","Wikipedian2","Wikispott",
                                    "Wilbysuffolk","Woe90i","ZooPro","7","Airplaneman","AlexandrDmitri","Amatulic","Arsenikk","Barek","BigDom",
                                    "Blurpeace","Bradjamesbrown","Bsadowski1","Bwilkins","Calmer Waters","Ceranthor","Connormah","Dabomb87","Dana boomer","Diannaa",
                                    "Eagles247","Elen of the Roads","Elockid","Eustress","Everyking","Excirial","Fainites","Father Goose","Favonian","Fetchcomms",
                                    "Floquenbeam","GorillaWarfare","Grondemar","HelloAnnyong","J04n","JamesBWatson","Jamesofur","Jmh649","Joe Decker","Jujutacular",
                                    "Kingpin13","Kww","Leonard^Bloom","Leyo","Looie496","Magog the Ogre","Mandsford","MGA73","Michig","Mike Cline",
                                    "Mkativerata","NativeForeigner","Nev1","Nikkimaria","Olaf Davis","Panyd","Phantomsteve","Polargeo","PresN","Rlendog",
                                    "Ron Ritzman","Shirik","Soap","Sphilbrick","Taelus","TFOWR","The Wordsmith","TheCatalyst31","Theleftorium","Thumperward",
                                    "Tide rolls","Tim Song","Vejvanƒçick√Ω","VernoWhitney","Waldir","Wifione","WOSlinker","07bargem","1234r00t","Access Denied",
                                    "Addihockey10","Adyniz","Aiken drum","Alan16","Alansohn","alexsautographs","ArcAngel","barts1a","Blanchardb","Bobby122",
                                    "Cgoodwin","Checker Fred","Cliffmore","Crotalus horridus","Danielspencer91","Darth Stabro","ddbruce","Dr Dec","Dylandlima","Ecw.technoid.dweeb",
                                    "Editorofthewiki","Endofskull","Eridani","Ezekiel63745","Falcon8765","Flushing258","Frozen4322","Geomapboy2","Ginbot86","Gobbleswoggler",
                                    "GSorbyDesroid","GSorbyDesroid 2","Hadger","Halgo123","Halil marx07","Herostratus","Immunize","Ipfreely555","JahaalChakravarti","Jc3s5h",
                                    "Jeffrey Mall","Jempcorp","Jerem43","Jmcw37","Joe Chill","Joe Gazz84","KhamaPula","Kingoomieiii","Kirachinmoku","Kirkoconnell",
                                    "KRSTIGER","Laptopmaker","Ling.Nut","Louis Taylor","Madhero88","Madokhn","Marcus Aurelius Antoninus","matt319","MC10","Merle Lang",
                                    "Mikael H√§ggstr√∂m","Minimac","MWOAP","Mysdaao","MZMcBride","NastalgicCam","Nations United","Navy blue84","Nosleep","Osarius",
                                    "Otherlleft","P Carn","Pepperpiggle","PopMusicWillNeverBeLowBrow","Porchcrop","ProcEnforce","Raaggio","RandomStringOfCharacters","Redthoreau","rp0211",
                                    "Rzrscm","S1312","S Marshall","Sam Blacketer","Saverx","ShawnIsHere","Silver seren","SJK","Skater","SMcCandlish",
                                    "SyedNaqvi90","T","TEK","Terrasidius","The Arbiter","The High Fin Sperm Whale","The Thing That Should Not Be","The Utahraptor","Thegoodlocust","Tommy2010",
                                    "Torchwoodwho","TransporterMan","Triona","Unionhawk","Venomcuz","White Shadows","Wiki Greek Basketball","Wikiwoohoo","Wilhelmina Will","William S. Saturn",
                                    "YOSF0113","Youndbuckerz","Yuvmil","2over0","Abecedare","AdjustShift","Admiral Norton","Al Ameer son","AlexiusHoratius","Amalthea",
                                    "Amorymeltzer","Arbitrarily0","Atama","Backslash Forwardslash","Beeblebrox","Bellhalla","Bettia","Billinghurst","Bob the Wikipedian","BOZ",
                                    "CactusWriter","Camw","Chamal N","Ched Davis","Climie.ca","Closedmouth","Cobi","Colds7ream","Cool3","CRGreathouse",
                                    "Davemeistermoab","decltype","Dinoguy1000","Drilnoth","Dumelow","Enigmaman","Explicit","Fastily","Fences and windows","FlyingToaster",
                                    "Foxy Loxy","Franamax","Fribbler","Fribbulus Xax","Ged UK","Geni","Graeme Bartlett","Hawkeye7","Jafeluv","Jake Wartenberg",
                                    "JamieS93","Jarry1250","JohnCD","Kanonkas","Kateshortforbob","Killervogel5","Killiondude","Kotra","Laser brain","Law",
                                    "LinguistAtLarge","Maedin","Malik Shabazz","Materialscientist","Maunus","Mazca","Mentifisto","Mfield","Mifter","Mikaey",
                                    "Mjroots","Mlaffs","MLauba","MrKIA11","Msgj","Mufka","MuZemike","Nja247","NuclearWarfare","OlEnglish",
                                    "Orlady","OverlordQ","Pastor Theo","Patar knight","Paxse","PeterSymonds","Plastikspork","R'n'B","Rambo's Revenge","RegentsPark",
                                    "Rjanag","RL0919","Ronhjones","Rosiestep","Runningonbrains","S@bre","Shubinator","Skomorokh","Sky Harbor","Smith609",
                                    "Someguy1221","Somno","SpacemanSpiff","Spinningspark","Steve","Tassedethe","Tcncv","Tedder","ThaddeusB","The Earwig",
                                    "The ed17","TheDJ","Tinucherian","Tnxman307","Toon05","Ucucha","Valley2city","Vianello","Wadester16","WereSpielChequers",
                                    "Willking1979","Wtmitchell","95jb14","A3RO","A new name 2008","Abce2","Accdude92","adamfinmo","Afaprof01","AgentB1",
                                    "Alexander.hugh.george","Altruism","Amlnet49","Andrewmc123","andrewrp","Ant2387","Arbiteroftruth","AresAndEnyo","AtheWeatherman","Audi152",
                                    "Baseball Bugs","Basket of Puppies","Bazj","Bcai388","Blakegripling ph","Blctc","BlueCaper","BQZip01","chase-mvp","ChildofMidnight",
                                    "Chzz","CrazyInSane","CrossHouses","Cryptic C62","Cyclonebiskit","Cyclonenim","DAFMM","DaL33T","Dalekusa","David Beals",
                                    "Dendodge","DotComCairney","Download","Dr. SzlƒÖchski","Dr.SzlƒÖchedzki","Einsteinbud","Enry≈´6473","Facha93","FredSmit","ft12",
                                    "Fuzzyhair2","Gaelen S.","Gaia Octavia Agrippa","Giangian15","Giants27","goalie1998","Gordonrox24","Graymornings","GrooveDog","Grsz11",
                                    "HappyCat12","Harish89","Headbomb","Hereford","I am watching you","I Seek To Help & Repair!","Ichwan Palongengi","IMatthew","ImperatorExercitus","ISD",
                                    "Itsmejudith","James Frankcom","Jfk52917","John-joe123","Katerenka","Kelapstick","Koman90","L07ChLeo3","Letsdrinktea","Llampadari",
                                    "LouriePieterse","Majorly","Manadude2","Mario1987","Markhurd","MathCool10","Mayalld","MisterWiki","Mixwell","Mohammad adil",
                                    "Mollymoon","Momusufan","Mr. moose","Mr Tan","Mrmuk","MyspaceMan12","Mythdon","Neckername","Neurolysis","Ojay123",
                                    "Ottava Rima","Parker1297","Paul2387","Policyofmankind","Pr3st0n","Pyfan","Raiku Lucifer Samiyaza","RayAYang","Raza0007","Red Thunder",
                                    "Renaissancee","Rockstone35","Roux","RuleOfThe9th","Salavat","Schmausschmaus","SE7","Sebwite","Sephiroth storm","Shark96z",
                                    "Shoessss","Snowded","SOPHIAN","Steve Crossin","Stevedietrich","Syjytg","Synergy","Tango","Taymaishu","Tdrss",
                                    "Tempodivalse","TenPoundHammer","Teratornis","Texcarson","The Black Rabbit of Inl√©","The C of E","The Cool Kat","The spesh man","The Transhumanist","tianhua1993",
                                    "Timmeh","TParis00ap","TreasuryTag","Tsepelcory","Tyw7","Until It Sleeps","Versus22","Vicenarian","Vitorbraziledit","Vivio Testarossa",
                                    "Volvo B9TL","VTomi","Wael.Mogherbi","Wetman88","Wikifan798","Wwesocks","WWEYANKS52","Wyatt915","Zink Dawg","ZooFari",
                                    "^demon","52 Pickup","Addshore","Aervanath","Aitias","AKeen","Ale jrb","Aleta","Alex.muller","Alexf",
                                    "Ameliorate!","AngelOfSadness","AniMate","Appraiser","Aqwis","Archtransit","Barneca","Bedford","Ben MacDui","Berig",
                                    "Bigtimepeace","BirgitteSB","Bjweeks","Blueboy96","Buckshot06","Cailil","Camaron1","Canley","CapitalR","Cbl62",
                                    "Cenarium","Chetblong","Choess","CIreland","Cirt","Ckatz","Cobaltbluetony","Daniel J. Leivick","Dank55","Davidgothberg",
                                    "DDima","Ddstretch","Deacon of Pndapetzim","DeadEyeArrow","Discospinster","Djsasso","Doczilla","Doug","Dougweller","Dravecky",
                                    "EdJohnston","Efe","EncMstr","Epbr123","Esanchez7587","Euryalus","EyeSerene","Firefoxman","Frank","Fritzpoll",
                                    "G.A.S","Gadget850","Gatoclass","Gazimoff","Gb","Gladys j cortez","Gonzo fan2007","Good Olfactory","GrahamColm","Gutza",
                                    "Gwen Gale","Happy-melon","Happyme22","Hdt83","Hersfold","Horologium","Huntster","Hurricanehink","Ice Cold Beer","Icestorm815",
                                    "Icewedge","Islander","It Is Me Here","J-stan","J.delanoy","J Greb","Jac16888","Jauerback","Jayron32","Jbmurray",
                                    "Jclemens","Jeepday","JGHowes","John Carter","Jonny-mt","JPG-GR","Juliancolton","Jza84","Kakofonous","Karanacs",
                                    "Kbthompson","Keeper76","Keilana","Kevin","Kim Dent-Brown","KnightLago","L'Aquatique","Lankiveil","LAX","Lazulilasher",
                                    "Lenticel","Lifebaka","Lomn","Lquilter","lustiger seth","Magioladitis","Malcolmxl5","Malinaccier","Martijn Hoekstra","Master of Puppets",
                                    "Matthewedwards","MBisanz","MBK004","Melesse","MilborneOne","Mitchazenia","Mizu onna sango15","Moni3","Nancy","Nousernamesleft",
                                    "OhanaUnited","Okiefromokla","Parsecboy","Paul Erik","Pb30","Pegship","Peripitus","Peteforsyth","Philosopher","Pinkville",
                                    "Poeloq","Protonk","R. Baley","Remember the dot","Risker","Rjd0060","Rodhullandemu","Roger Davies","Rudget","Ruslik0",
                                    "Sabine's Sunbird","Sarcasticidealist","Scarian","Scott5114","Seddon","Seicer","Sephiroth BCR","Seraphim Whipp","Seresin","Sgeureka",
                                    "SheffieldSteel","shoeofdeath","SilkTork","Slp1","Smalljim","Smashville","SorryGuy","SoWhy","Soxred93","Spencer",
                                    "StephenBuxton","Steven Fruitsmaak","Stwalkerster","Tadakuni","Tanner-Christopher","Tanthalas39","thedemonhog","Thehelpfulone","Thingg","Tiptoety",
                                    "Tivedshambo","Toddst1","TomStar81","Travellingcari","TravisTX","Ultraexactzz","VanTucky","Victuallers","WBOSITG","Wehwalt",
                                    "Werdna","WilliamH","Xavexgoem","Xenocidic","Xymmax","Ynhockey","Zedla","Zeibura","21655","A Cool Editor",
                                    "AaronSchell","Abd","ACBest","AdirondackMan","Adolphus79","Alan De Smet","AlanH","AlbertHerring","Ali'i","Ammar gerrard117",
                                    "Anon126","Arienh4","Asenine","Autocracy","Avruch","Basketball110","bassman91","Benjah-bmm27","Bigvinu","Billy",
                                    "Biruitorul","Bjaco18","Bluegoblin7","Blueking12","BMWSAAB","Borgarde","Brianreading","BritandBeyonce","Bugalugs13","Burhan Ahmed",
                                    "Camaeron","Carter","Cedarvale1965-08","Certified.Gangsta","ChuckCoke","CJ2005B","Clpo13","CompuHacker","ComputerGuy890100","Conker01",
                                    "Coppertwig","Cosmic Latte","Crash Underride","Cream","crimsonterminator1000","Cssiitcic","Cubs Fan","CWii","CWY2190","D-Day",
                                    "\"Dagoth Ur, Mad God\"","Danielaustinhall12","Danielfolsom","Darth Mike","Davnel03","Dell970","Derfboy","Desalvionjr","Dihydrogen Monoxide","Dpshuler",
                                    "Dreamafter","Dustihowe","Dycedarg","Dylant07","Earthbendingmaster","Eastlaw","EclipseSSD","Ecoleetage","Ed Poor","Elbutler",
                                    "EricV89","Erik the Red 2","ESCStudent774441","Etan","EvilWendyMan","Fatal!ty","Fercho85","Fifaworld07","Finalnight","Floaterfluss",
                                    "Footballfan190 2","Footballfan190","Footballfan190 4","Fordmadoxfraud","George The Dragon","GO-PCHS-NJROTC","Golich17","goodandhonestwhig","Goodnight123","Grey Wanderer",
                                    "gromlakh","Gtstricky","Guest9999","Gwynand","HalfShadow","Helpfulweasal","\"Hennessey, Patrick\"","Highfields","HisSpaceResearch","HK22",
                                    "hockeypuck990","How do you turn this on","HPJoker","Hyano czespony","i123Pie","Iamawesome800","Ilyushka88","Imperial Star Destroyer","InDeBiz1","\"Inferno, Lord of Penguins\"",
                                    "Islaammaged126","Izzy007","Jagun","Jamesontai","JayJ47","JeanLatore","Jet","John254","Johnnyjoe23","Jordan Payne",
                                    "Joseph Solis in Australia","Joshuarooney","Jouster","JRH95","Juggernaut0102","Jupiter Optimus Maximus","Justin Eiler","K50 Dude","Kalajan","Kefo77",
                                    "Kerotan","Kinderboy","Kourosh ziabari","Krm500","Kubek15","LAAFan","Lady Aleena","Latics","Lawrence Cohen","Leolisa1997",
                                    "Llamadog903","Londonfella","Madviolinist","Malleus Fatuarum","Mark t young","Masterpiece2000","Mastrchf91","matt037291","Maverick Leonhart","MHLU",
                                    "Milk's Favorite Cookie","Mind meal","Morbidthoughts","Morhange","Mr. IP","mr kc","Mr Senseless","MrFish","Mvjs","Mww113",
                                    "MyNameIsKyle","Naerii","NASCAR Fan24","nassir49","Natl1","Nick carson","NitrogenTSRH","No1lakersfan","NonvocalScream","norge0209",
                                    "NorthernThunder","Nothing444","Nwwaew","O Keyes","Obaidz96","Ohmpandya","Olz06","Ozzaroni","Paste","PastorMatt",
                                    "Pathfinder2006","Pattav2","paulyb","PeeJay2K3","Plasticup","Plyhmrp","PoinDexta1","Pookeo9","Prashanthns","Pumpmeup",
                                    "Qaddosh","R","Raggonix","Rappingwonders","RC-0722","readeww","Realist2","Red Phoenix","Redfarmer","Redmarkviolinist",
                                    "RFerreira","Rgoodermote","Richard0612","rio de oro","RMHED","Ro098","robfergusonjr","Ryan","RyanLupin","RyRy",
                                    "Save the Humans","Sceptre","Scetoaux","SchfiftyThree","Scienceman123","SeanMD80","Sethdoe92","Sfd1905","Shapiros10","Sharkface217",
                                    "Shoemaker's Holiday","SimpsonsFan08","Skyler13","Slgrandson","Snocrates","Sock's Favorite Puppet","StephenHjellum13","StewieGriffin!","Stormtracker94","Strennman",
                                    "Suntag","SynergeticMaggot","Termer","Textbook","Tharnton345","The Great Editor In Chief","TheBlazikenMaster","TheNewPhobia","Thfrang","ThinkBlue",
                                    "TimothyJacobson","Tinkleheimer","Tkgd2007","Toyotaboy95","Trampikey","Treelo","Trillio","Triwbe","Tutthoth-Ankhre","Two-face Jackie",
                                    "Undead warrior","Unisouth","Unknownquinones","Urban Rose","UserD≈ì","Vikrant Phadkay","Vishnava","VivioFateFan","WarthogDemon","WeBuriedOurSecretsInTheGarden",
                                    "Wikidudeman","Wikieditor222","Wisdom89","wolfpawz","WWEFAN99","Xp54321","zeuspitar","Zginder","Ziggy Sawdust","#NAME?",
                                    "A. B.","AA","Aarktica","Acalamari","Accounting4Taste","Acroterion","Adam Cuerden","Adambro","Addhoc","After Midnight",
                                    "AGK","Ais523","Akhilleus","Akradecki","Alasdair","Alex valavanis","Alison","AliveFreeHappy","Alvestrand","Amire80",
                                    "Anas Salloum","AndonicO","Andrew c","Andrwsc","AnemoneProjectors","Anetode","Angelo.romano","Angusmclellan","Anonymous Dissident","Anthony.bradbury",
                                    "Anthony Appleyard","AQu01rius","Arctic.gnome","Arjun01","Arkyan2","ArnoldReinhold","Athaenara","AuburnPilot","Audacity","Awiseman",
                                    "AzaToth","Balloonman","Bduke","Bearian","Beetstra","Bencherlite","Bibliomaniac15","BigDT","BigHaz","BigrTex",
                                    "Bjelleklang","Bkell","Black Falcon","Blood Red Sandman","Bobak","Bongwarrior","BozMo","BradBeattie","BrendelSignature","Brian New Zealand",
                                    "Brianga","Bubba hotep","Butseriouslyfolks","C.Fred","Caknuck","Calliopejen1","Canadian Paul","Carabinieri","Carcharoth","Caribbean H.Q.",
                                    "Carioca","Carlosguitar","carlossuarez46","Casliber","CattleGirl","\"Chase me ladies, I'm the Cavalry\"","Chochopk","Chris G","Chrislk02","ChrisTheDude",
"Christopher Parham","Chunky Rice","Citicat","CJLL Wright","Ck lostsword","CloudNine","CMummert","Coelacan","Coren","Crazytales",
"Cremepuff222","Croat Canuck","Crum375","Cuchullain","Danaman5","Daniel Case","DanMS","Danny","DarkFalls","Darthgriz98",
"Davewild","David D.","David Eppstein","David Fuchs","Dekimasu","Delldot","DerHexer","Deryck Chan","Dfrg.msc","DGG",
"Dgies","Dlohcierekim","DMacks","DO11.10","DoomsDay349","Dppowell","Dreadstar","DrKiernan","Dweller","E",
"east718","Edison","Edokter","Eleassar","EliminatorJR","ElinorD","Eliz81","Elkman","Elonka","Eluchil404",
"Emperor","EncycloPetey","Ericorbit","Espresso Addict","Esprit15d","Ev","Evilclown93","Eyrian","Fabrictramp","Faithlessthewonderboy",
"Feydey","FisherQueen","Fishhead64","Flyguy649","Fram","FT2","Fuhghettaboutit","Fvasconcellos","Gaius Cornelius","Garion96",
"GDonato","Geniac","Geometry guy","Georgewilliamherbert","Gilliam","Gimmetrow","GlassCobra","Goodnightmush","Graham87","Grant65",
"Greeves","Haemo","Harryboyles","Hbdragon88","Heimstern","Heligoland","Hemlock Martinis","Henrik","Herbythyme","Hex",
"Hiberniantears","\"Hit bull, win steak\"","Hu12","Hut 8.5","Ikiroid","Ioeth","Iridescent","Irishguy","Isotope23","J Milburn",
"James086","Jaranda (reconfirmation)","Jayvdb","Jehochman","Jerry","Jersey Devil","Jersyko","Jesse Viviano","JForget","JHunterJ",
"Jj137","Jmlk17","JodyB","Jogers","John Reaves","Jon513","Jreferee","Kafziel","Kaiser matias","Kane5187",
"Kathryn NicDh√†na","Keith D","KFP","Khukri","Kicking222","KieferSkunk","Kinu","Kizor","KrakatoaKatie","Kralizec!",
"Krimpet","Kubigula","Kurt Shaped Box","Kuru","Kwsn","LaraLove","Leebo","LessHeard vanU","Lid","Llama man",
"Lradrama","Lucasbfr","Lyrl","Madman","Magnus animum","Mallanox","Marasmusine","markles","Marskell","Masamage",
"Masem","MastCell","Matt Britt","Mattbr","MatthewUND","Mattinbgn","MaxSem","Mecu","Melburnian","Meno25",
"Metropolitan90","Michael Greiner","Michaelas10","MichaelBillington","Mike Peel","Mikeblas","MJCdetroit","monotonehell","Moonriddengirl","Moreschi",
"MoRsE","Mr.Z-man","Mtmelendez","Mysid","Nat","Natalie Erin","Navou","Nehrams2020","Neranei","Newyorkbrad",
"Nick Dowling","Night Gyr","Nightscream","Nihiltres","Nikki311","Nilfanion","Nmajdan","NrDg","Number 57","Nyttend",
"Ocatecir","Od Mishehu","Oldelpaso","Oldwindybear","Orangemike","Orderinchaos78","Oxymoron83","Pascal.Tesson","Pastordavid","Pats1",
"Pax:Vobiscum","PeaceNT","Pedro","Penwhale","Persian Poet Gal","Philippe","Picaroon9288","Pigman","PrimeHunter","Prolog",
"ProveIt","PullToOpen","Qwghlm","Ragesoss","Random832","Raymond arritt","Rebelguys2","Recurring dreams","RedirectCleanupBot","Reedy Boy",
"Resolute","Rettetast","Revolving Bugbear","Riana dzasta","Richardshusr","Rifleman 82","Rigadoun","Rkitko","Rklawton","Rlevse",
"RockMFR","Ronnotel","Royalbroil","Ruhrfisch","Ryanpostlethwaite","Ryulong","Salix alba","Samulili","Sanchom","Satori Son",
"SatyrTN","Savidan","SB Johnny","SchuminWeb","Schutz","Scientizzle","Searchme","Seattle Skier","SebastianHelm","Selket",
"Seraphimblade","SGGH","Shadow1","ShadowHalo","Shimeru","Shirahadasha","Shyamal","SirFozzie","SkierRMH","Slakr",
"Slumgum","Snowolf","Soumyasch","Spartaz","Spebi","Spellcast","SpuriousQ","SQL","Sr13","ST47",
"Staecker","Stephan Schulz","Stephen","Swatjester","Tabercil","Tbo 157","TeaDrinker","TerriersFan","The-G-Unit-Boss","The Placebo Effect",
"The Rambling Man","The Random Editor","the undertow","Thespian","Tikiwont","TimVickers","Tony Fox","Tra","Trebor Rowntree","Trusilver",
"TSO1D","TwinsMetsFan","Useight","Vassyana","VegaDark","Veinor","Versageek","VirtualSteve","Visviva","Wafulz",
"Waggers","Walton monarchist89","Walton One","Wassupwestcoast","William Pietri","WilyD","Wimt","Wizardman","WJBscribe","WODUP",
"Woodym555","Wrp103","Xdamr","xDanielx","Xiner","Xnuala","Yamamoto Ichiro","Yandman","Yannismarou","Yonatan",
"Zzuuzz","53180","A Raider Like Indiana","Abela2006","Adun12","Aflumpire","Ag√ºeyban√°","Ahadland1234","Airbus A300","AKMask",
"Aktron","Alex43223","Ali","Amarkov","Anthony5429","Anthony cfc","Anynobody","AquaStreak","Arkyan","astroview120mm",
"Avant Guard","Averross","Azuran","Badlydrawnjeff","Ben","Betacommand","bfissa","BlackBear","BlakeCS","Bobes66",
"bobsmith319","Booksworm","Booyabazooka","Boricuaeddie","BostonMA","Bouncingmolar","BovineBeast","brettzwo","Brylcreem2","Budgiekiller",
"Bushcarrot","BYMAstudent","Caldorwards4","Captain panda","Captmondo","Caribbean1","Carterdriggs","CastAStone","Celticfan383","Ceres3",
"Chacor","Chamillitaryboi94","Chris is me","Chrishomingtang","Chuckfromchan","CJMiller","Clamster5","Clawson","Cocoaguy","Codelyoko193",
"Cometstyles","Communist47","Crassic","CRocka05","crownofworms","CyclePat","Czac","Czarbender","Dagadt","Daniel.Cardenas",
"Danielrocks123","Danswiki","Dantheman531","Dark Dragon Flame","Darkest Hour","Daven200520","David.Mestel","Davnel03 3","Davy1132","Dev920",
"Diez2","DOSGuy","Doyley","Dream out loud","Drmaik","Drumlineramos","DvDknight","Dynaflow","Dynamictwo-o","EastGermanAllStar",
"Edmundkh","EdwinCasadoBaez","eggwo","Emesee","Errabee","Eukesh","Extranet","Fan-1967","FastLizard4","Ferrett3",
"Fightindaman","Finale Wiki Geek","FirefoxRocks","Flameviper","Flaminglawyer","Flubeca","Foundby","Froth","Fyre2387","gagueci",
"Gay Cdn","Geoffr","Gizwidget","Gndawydiak","Goodshoped35110s","Gp75motorsports","Gracenotes","GreaterWikiholic","greenboxed","Groupempty",
"Grubber","Gurch","Hardcore Hak","HarryMaxwell","Hastingssaxonspride","hehehehehehehe","Hencetalk","Hiddenhearts","Hiphopchamp","Hirak 99",
"holmes.sherlock","Hornetman16","HyperSonicBoom","Ibaranoff24","IBeatAnorexia","Imdanumber1","Ineversigninsodonotmessageme","IronDuke","Ishikawa Minoru","Ispy1981",
"IvoShandor","Jakew","Jet123","JetLover","Jetstar888","Jftsang","Jhfireboy","Joebengo","Johnny Au","Jonathan",
"Jonjonbt","Jor","Josephtheboheme","JP06035","Jrockley","Judae1","JuJube","Just H","JXM","Karrmann",
"Kermanshahi","KGV","King √ì√∞inn The Aesir","Kitia","Knobbie10","Kntrabssi","Kornfan71","KyraVixen","Kyriakos","Kzrulzuall",
"Lake54","Laleena","Lankybugger","Lazylaces","Limetolime","Lincalinca","Loom91","Lord Hawk","Luckyluke","luvcraft",
"Lwarf","Maelwys","MakeChooChooGoNow","Marcschulz","MarSch","Martinultima","MasterA113","mattbroon","MatthewFenton","Mattl2001",
"Max Naylor","mbralchenko","Mehrshad123","Melsaran","Member","mentaka","MER-C","Mercury","Michaelbusch","Michaelsanders",
"Michfan2123","microchip08","MiddleEastern","Mike33","Mike6271","Minesweeper.007","Miranda","Missingno390","MMAfan2007","Moralis",
"Mrld","Mschel","munkee madness","N","N3mm","Nardman1","Nat.tang","Nat Wolff","Nburden","Nduell",
"Nenyedi","NHRHS2010","NicolasLord","Nima Baghaei","Nimrauko","nuclearj","Oddmartian2","Oliver202","oliver3669","oo7565",
"Otto4711","owie123","Ozgod","P.B. Pilhet","Padillah","Parker007","Patchouli","Patricknoddy","PaxEquilibrium","Peregrine Fisher",
"Perspicacite","Philip Gronowski","Phoenix2","Pie Man 360","Plainnym","Plm209","PNiddy","PrestonH","ProtectionBot","Psdubow",
"Pupster21","Qst","Quatreryukami","Racepacket","Randomjack","Reaper X","Retiono Virginian","RevRagnarok","Rhythmnation2004","Richard n",
"Roastytoast","Ryan524","Ryan Keyes","Ryanzilla13","Saint-Paddy","Sam 1123","Sangak","Sasha Callahan","Saturation2","Saudiqbal",
"Scharks","sepehrsh","Serpent's Choice","Shimdidly","Simply south","Sir james paul","Siva1979","SJP","Skully Collins","SLSB",
"Smcafirst","Socks 01","Soman","Somitho","Sony-youth","Sox23","Spartan-James","SpecialAgentUncleTito","SteveMcSherry","Street Scholar",
"Styrofoam1994","SunStar Net","Superbfc","Surplu","T-dot","Taborlechner","Tarret","TeckWiz","TehBrandon","Tellyaddict",
"TempDeletionBot","Teniii","The Haunted Angel","The Raven's Apprentice","Thebestkiano","TheFearow","TheIslander","TheListUpdater","Thenthornthing","TheOkayThrill",
"Thomasiscool","TimySmidge","TioChaka","tjstrf","Tohru Honda13","TomasBat","TonyTheTiger","Touch Of Light","TREYWiki","Trumpetband",
"U-Two","Uga Man","Vanilla2","Veesicle","victoria uni","Vintei","Vishwin60","Vistro","W1k13rh3nry","Wandalstouring",
"Wantok","Wenli","Whiteandnerdy111","Wikihermit","Wikipedialuva","WikipedianProlific","Wikipediarules2221","Wikisteph888","Wikitank","Wildnox",
"Wildthing61476","will merchant","WilliamKF","Wizardry Dragon","Wooyi","Yao Ziyuan","yatesy1988","Yonidebest","Yuser31415","zach111493",
"Zachary crimsonwolf","Zazzer","(aeropagitica)","Aaron Brenneman","Adambiswanger1","Admrboltz","Aecis","Agathoclea","Aguerriero","Aksi great",
"Aldux","Alex9891","Alex Bakharev","Alphachimp","Amalas","Ambush Commander","AmiDaniel","Andrew Levine","AndyZ","AnonEMouse",
"Anonymous editor","Art LaPella","Arthur Rubin","Ashibaka","Asterion","Atlant","Aude","Avraham","AYArktos","Babajobu",
"Banes","Banno","Bastique","Bbatsell","Ben W Bell","Blnguyen","Bobet","Bobo192","Bookofjude","Borisblue",
"BrownHairedGirl","Buchanan-Hermit","Bucketsofg","Cactus.man","\"Can't sleep, clown will eat me\"","Canadian-Bacon","CanadianCaesar","Cantthinkofagoodname","Carnildo","CBDunkerson",
                                    "Cbrown1023","Centrx","Ceyockey","Chairboy","Chaser","Chick Bowen","Cholmes75","ChrisGriswold","Christopher Sundita","Circeus",
                                    "Cohesion","Conscious","Consumed Crustacean","Coredesat","Cowman109","Crazycomputers","Crzrussian","Cuivienen","Cyde","DaGizza",
                                    "DakotaKahn","Dalbury","Daniel Olsen","Daveydweeb","David Kernow","Davidruben","Deckiller","Deepujoseph","Deiz","Deskana",
                                    "Deville","Dijxtra","Dina","Doug Bell","Dsmdgold","Duja","Durova","Dustimagic","DVD R W","Eagle 101",
                                    "Edgar181","Elf-friend","Encephalon","ERcheck","ESkog","Essexmutant","EurekaLott","EVula","EWS23","Extraordinary Machine",
                                    "Ezeu","Fang Aili","Femto","Fir0002","Firsfron","FloNight","Flowerparty","FrancisTyers","Fred chessplayer","Fropuff",
                                    "Future Perfect at Sunrise","Ganeshk","Gator1","GeeJo","Gflores","GIen","Ginkgo100","Gnangarra","Gogo Dodo","Goldom",
                                    "Grandmasterka","GRBerry","Grendelkhan","Gryffindor","Guanaco","Guinnog","Gwernol","Haukurth","Heah","HereToHelp",
                                    "HighInBC","Hoary","Hoopydink","Humus sapiens","Husnock","Husond","Ian13","IanManka","Idont havaname","Ilmari Karonen",
                                    "InShaneee","Interiot","Irongargoyle","Ish ishwar","J.smith","J Di","Jaranda","JDoorjam","Jedi6","JLaTondre",
                                    "Joelr31","Johan Elisson","Joke137","Jonathunder","Joshbuddy","JoshuaZ","Josiah Rowe","JPD","Jusjih","JzG",
                                    "Kaisershatner","Kcordina","Keenan Pepper","Khoikhoi","KillerChihuahua","Kilo-Lima","Kimchi.sg","KimvdLinde","King of Hearts","Kingboyk",
                                    "Kjkolb","Konstable","Kpjas","Kukini","Kungfuadam","Kusma","Kylu","Lar","Larry V","Laurascudder",
                                    "Lethe","Lightdarkness","Ligulem","LiquidGhoul","Lord Voldemort","Lostintherush","Luna Santin","Makemi","Mangojuice","Mark83",
                                    "Martinp23","Martyman","Master Jay","Mathwiz2020","MCB","Mdd4696","Meegs","Melchoir","Merope","Messedrocker",
                                    "Metamagician3000","Metros232","Mets501","Mike 7","Mike Selinker","MisfitToys","Misza13","MPF","Mr. Lefty","MrDarcy",
                                    "Mtz206","Myleslong","Naconkantari","Nae'blis","Natalya","NawlinWiki","NCurse","Netsnipe","Nightstallion","Nihonjoe",
                                    "Nishkid64","Nixdorf","No Guru","NoSeptember","Obli","Ohnoitsjamie","Olessi","Opabinia regalis","Oscarthecat","Osgoodelawyer",
                                    "Pagrashtak","Paolo Liberatore","Pengo","Pepsidrinka","Peruvianllama","Petros471","Pgk","Phaedriel","Philip Baird Shearer","Physicq210",
                                    "Pilotguy","Plange","Prodego","ProhibitOnions","Proto","PS2pcGAMER","Pschemp","Punkmorten","Quarl","R.Koot",
                                    "RadioKirk","Rama's Arrow","RasputinAXP","Raven4x4x","Redvers","Renata3","Renesis13","RexNL","ReyBrujo","Robdurbar",
                                    "Robth","Rockero","Rockpocket","Rogerd","Royalguard11","Royboycrashfan","Rspeer","Runcorn","Rune.welsh","RyanGerbil10",
                                    "Samir (The Scope)","Samsara","Samuel Blanning","Sandstein","Sarah Ewart","Saravask","Saxifrage","Scm83x","Sean Black","Silence",
                                    "Silsor","Sir Nicholas de Mimsy-Porpington","Sjorford","Smurrayinchester","Snoutwood","SoothingR","Sreed1234","Srikeit","Staxringold","Steel359",
                                    "Steinsky","Stemonitis","Stifle","StuffOfInterest","Superm401","Tangotango","Tariqabjotu","Tawker","Teke","TexasAndroid",
                                    "Thatcher131","The JPS","theProject","TigerShark","Tijuana Brass","TimPope","TKD","Tom harrison","TomTheHand","Tone",
                                    "Tonywalton","Tr√∂del","Trialsanderrors","Turnstep","Tyrenius","Tznkai","UkPaolo","Vary","Vegaswikian","Viridae",
                                    "W.marsh","Wangi","Water Bottle","WAvegetarian","Wgfinley","Where","Whouk","Wickethewok","Wiki alf","William M. Connolley",
                                    "Winhunter","Wknight94","Wouterstomp","Wwwwolf","Xaosflux","Xoloz","Xyrael","Yamla","Yanksox","Yomangani",
                                    "Youngamerican","Zsinj","4836.03","9cds","A Link to the Past","Aaron teh tennisman","AaronS","Abcdefghijklm","Abu badali","Ac1983fan",
                                    "Acebrock","Adam1213","addatron","Agateller","Aido2002","AKGhetto","Alan Liefting","Aleenf1","Alfakim","Alphax",
                                    "Ambuj.Saxena","Amgine","AMK152","Amynewyork4248","Andreasegde","Andy5190","Andypandy.UK","Anglius","AntoineJ","Aranda56",
                                    "asams10","Astanhope","Axiomm","AzaToth (2)","B&W Anime Fan","Bart133","benon","Benon2","Benon3","Benon4",
                                    "Benon5","Bg","Bigtop","Bigtop (2nd nomination)","BlackJack","Bling-chav","Bobabobabo","Bormalagurski","Bornhj","Bottesini",
                                    "Bpazolli","Brainhell","Brendenhull2","Brossow","Brusselsshrek","Bugs5382","Cameron Nedland","\"Can't sleep, clown will eat me too\"","Catamorphism","Cchan199206",
"Ccool2ax","Chad1m","Chaz365","Chazz88","CheNuevara","Christopherlin","CJ King","Cjmarsicano","Computerjoe","Conrad Devonshire",
"ContagiousTruth","Cookiecaper","Cooksey","CorbinSimpson","Crawfordknights","Crazytales56297","Crisspy","CrnaGora","Crystallina","CTSWyneken",
"CyberSkull","Cynical","Dangherous","Daniel 123","Dar-Ape","DarknessLord","DarthVader","Daveswagon","DavidJJJ","dbertman",
"DChiuch","Deeptrivia","DeltaSlaya","Deon555","Dewet","Digitalme","DINOMAN","Djr xi","DLJessup","Dmlandfair",
"Doctor Evil","Doktorbuk","downtowndontay","Drdisque","DRosenbach","Drumguy8800","DuctoMan16","Dueyfinster","Ec5618","Electricbassguy",
"Emt147","Emt1472","Encyclopedist","Eternal Equinox","Evadb","EvocativeIntrigue","Exir Kamalabadi","exvicious","Fetofs","Flameviper12",
"Flameviper X-1","Flarn2005","Folajimi","Folajimi2","Foxearth","FrankWilliams","Fritz Saalfeld","Fu kinell","Funnybunny","Ganfon",
"Gangsta-Easter-Bunny","GangstaEB","Gary Kirk","Gene Poole","General Eisenhower","Genisock2","Geo.plrd","Getcrunk","GHe","griffjam",
"grika","Haham hanuka","Hamedog","Hello32020","Helohe","Hexagon1","Hezzy","HighwayCello","Hmrox","HolyRomanEmperor",
"I-2-d2","Iced Kola","Icelandic Hurricane","Idleguy","ILovePlankton","Infinity0","Information Center","Invisible Robot Fish","Jake0geek","JakeDHS07",
"James Anatidae","Jamyskis","Jasenlee","Jason Potter","Jayanthv86","Jc37","JD UK","jesterjester","Jesus on Wheels","Jflash",
"Jimwitz","Joan53","joeferret","John Anderson","Jonathan235","Joturner","jstupple7","Jtkiefer","Juro","JustPhil",
"Karmafist","katieh5584","Kc9cqj","keeleysam","Keldan","Kevin Baas","Kf4bdy","KI","King Toadsworth","Kizzle",
"Kku","kku2","klingoncowboy4","Kseferovic","Lambertman","larsinio","laurenceandrews","lavakille","Lcarsdata","Leotolstoy",
"Liberal 2006","Liyster","Locke Cole","London UK","Lotsofissues","LtPowers","Lulu of the Lotus-Eaters","M1ss1ontomars2k4","M Johnson","Mac Davis",
"madcowpoo","Malber","Maltesedog3","Maltesedog","Markovich292","Martial Law","Matt Yeager","Maxamegalon2000","Mb1000","Mboverload",
"mcepitome","Mdcollins1984","Me and my robot","Megaman Zero","MegamanZero","Memmke","Micoolio101","Mike1","Mikedk9109","MilkMiruku",
"Minan","Mipadi","mlc409","Moe Epsilon","Morphh","Movementarian","Mrbowtie","Mushrambo","Naan Kadavul","NickCatal",
"NickCatal2","NightDragon","Nookdog","Northenglish","Ombudsman","Osbus","Patchouli2","Paul Cyr","PaulWicks","Pegasus1138",
"Peteg913","PHDrillSergeant","Piemanmoo","Pikminlover","Platypus222","Pmanderson","Poetlister","POLLUX","Popcorn2008","Post Falls Man",
"Preslethe","PuckMV","Punk Boi 8 2","Punk Boi 8","Qrc2006","R.D.H. (Ghost In The Machine)","RAbbott","Ramsquire","Ramsquire2","Randall Brackett",
"RandyWang","Rat235478683","RelentlessRouge","Remember","Rewired","RGTraynor","Ricardo Lagos","Rmky87","Rmrfstar","Robchurch",
"Robert McClenon","Robert Moore","Rock's rock","Rogerthat","ronan.evans","Rory096","Salman01","SaltyWater","Sam Spade","Samuelsen",
"SaxTeacher","Schzmo","Schzmo2","Schzmo3","Sean gorter","Selmo","Shmirlywhirl","ShootJar","Simetrical","Simpsons contributor",
"SkerHawx","Slashme","Slicky","Slyder Pilot","Smitty494","SoM","Son of a Peach","Son of a Peach II","Spawn Man","Splinter",
"Stephen B Streater","Stevage","SteveBaker","Steveo2","Stevietheman","Stlet.Rozinsky","Striver","Sugarpine","Sukh","Sunfazer",
"SupaStarGirl","SVera1NY","SWD316","TawkerbotTorA","Tdxiang","Teh tennisman","TehKewl1","Terence Ong","Terenceong1992","Terrillwhite",
"The Bread","The Fish","The Halo","The Hybrid","The Republican","The Thadman","The Thadman2","the truth from texas","The Uber Ninja","The Wookieepedian",
"The Wookieepedian2","TheM62Manchester","Thetruthbelow","Tmalmjursson","Tmorton166","TodorBozhinov","Tom walker","Topaz","TruthbringerToronto","Trysha",
"Tuspm","Tv316","Tvaughn05","Tzaquiel","Underneath-it-All","Unixer","Urthogie","Veracious Rey","WCityMike","Weirdy",
"Werdna648","Weyes3","WikiCats","WikiMan53","Wikipeedio","WillC","Williamborg","Xchrisblackx","Xerocs","Xerocs2",
"Yeltensic42.618","Zack3rdbb","Zanaq","Zappa.jake","Zapptastic","zhudyzhu","Zpb52","23skidoo","A Man In Black","ABCD",
"Acetic Acid","Adashiel","Alabamaboy","Alai","Alhutch","AlistairMcMillan","Alkivar","Allen3","Alteripse","Ancheta Wis",
"Andrew Norman","Android79","Angr","Antandrus","Arcadian","Asbestos","Ausir","Awolf002","BanyanTree","BaronLarf",
"BD2412","Beland","Bhadani","Biekko","BillyH","Bluemoose","Bmicomp","Bogdangiusca","BorgHunter","BorgQueen",
"Bovlb","Bratsche","Brendanconway","Brian0918","Brian Kendig","Briangotts","BrianSmithson","Brighterorange","BrokenSegue","Brookie",
"Bumm13","Bunchofgrapes","Burgundavia","Cacycle","CambridgeBayWeather","Canderson7","Capitalistroadster","Carbonite","Cburnett","Cdc",
"Cedar-Guardian","Celestianpower","CesarB","Changlc","Clarkk","Cleared as filed","CLW","Cnwb","Commander Keane","Cryptic",
"Curps","Cyberjunkie","Dan100","DanielCD","Darwinek","dave souza","David Levy","Dbenbenn","Dbiv","Deathphoenix",
"Deltabeignet","Demi","Denelson83","DESiegel","Dmcdevit","Doc glasgow","DragonflySixtyseven","Dragons flight","DrBob","Drini",
"Durin","Dvyost","Edcolins","Edward","EdwinHJ","Egil","El C","Ellsworth","Enochlau","Essjay",
"Eugene van der Pijll","EvanProdromou","Evercat","Evil Monkey","Evilphoenix","Extreme Unction","Fastfission","Fawcett5","FayssalF","FCYTravis",
"FeloniousMonk","Fernando Rizo","FireFox","Flcelloguy","Freakofnurture","Freestylefrappe","FreplySpang","Friday","Func","Furrykef",
"Fvw","Gabbe","Garzo","Gdr","Goodoldpolonius2","GraemeL","Graft","GregAsche","GregRobson","Grenavitar",
"Grm wnr","Ground Zero","Grue","Grutness","GTBacchus","Guettarda","Gurubrahma","Gyrofrog","Hall Monitor","Hamster Sandwich",
"HappyCamper","Harro5","Hashar","Hedley","Henrygb","Hermione1980","HorsePunchKid","Howcheng","Humblefool","Ianblair23",
"Ianbrown","Icairns","IceKarma","Improv","Ingoolemo","Inter","Ixfd64","Izehar","Jacoplane","JamesTeterenko",
"Jareth","Jaxl","Jcw69","Jdavidb","Jeffrey O. Gustafson","JeremyA","JesseW","Jinian","JIP","Jitse Niesen",
"Jkelly","Jni","Jnothman","JoanneB","Joe Beaudoin Jr.","Johann Wolfgang","Johntex","JoJan","Jondel","Joolz",
"Josh Grosse","Journalist","Jredmond","JRM","Justinc","JWSchmidt","JYolkowski","K1Bond007","Kaldari","Katefan0",
"Kbdank71","Kbh3rd","Khaosworks","Kirill Lokshin","Kmccoy","Knowledge Seeker","KnowledgeOfSelf","Kwamikagami","Kzollman","Lacrimosus",
"Lbmixpro","Lectonar","Leithp","Linuxbeak","Lommer","Longhair","LordAmeth","Lucky 6.9","Luigi30","Lupin",
"Madchester","Mailer diablo","Mairi","Malathion","Malo","Marianocecowski","Marine 69-71","Mark Dingemanse","MarkGallagher","MarkSweep",
"Marudubshinki","Master Thief Garrett","MC MasterChef","Mel Etitis","Miborovsky","Mike Rosoft","Mindmatrix","Mindspillage","Mo0","Moriori",
"Mulad","Mushroom","Musical Linguist","Mysekurity","Mzajac","Nabla","Nandesuka","Natalinasmpf","Necrothesp","Ngb",
"NicholasTurnbull","Nickptar","Nickshanks","Nlu","NSLE","Nufy8","Nv8200p","Oleg Alexandrov","Omegatron","Orioane",
"Oven Fresh","OwenX","Pablo-flores","Pamri","Pathoschild","Paul August","Petaholmes","Pharos","Phil Boswell","Phils",
"Philwelch","Phroziac","Physchim62","Pjacobi","PRueda29","Psy guy","Qaz","R. fiend","R3m0t","Radiant!",
"Ragib","Ral315","Rama","Ramallite","Redux","Redwolf24","Refdoc","Reflex Reaction","RHaworth","Rholton",
"Rich Farmbrough","Rick Block","Ricky81682","Rje","RJFJR","Rlquall","RN","RobertG","RobyWayne","Ronline",
"RoyBoy","RoySmith","Rschen7754","Rx StrangeLove","Sam Hocevar","SamuelWantman","Sango123","Sasquatch","SCEhardt","Schissel",
"Scimitar","Scott Burley","ScottDavis","SCZenz","Seabhcan","Sebastiankessel","Sesel","Sfoskett","Shanel","Shanes",
"Shauri","Sherool","Shimgray","Shreshth91","Sjakkalle","Slambo","SlimVirgin","Smoddy","Sn0wflake","Snottygobble",
"SoLando","Sortior","Spangineer","Splash","Sundar","Syrthiss","Ta bu shi da yu","TenOfAllTrades","Thames","The Land",
"The Singing Badger","The Tom","Thebainer","TheCoffee","TheoClarke","TheParanoidOne","Thorpe","Thryduulf","Thunderbrand","Timrollpickering",
"Tomf688","Tony Sidaway","Tregoweth","Trevor macinnis","Triddle","Trilobite","TShilo12","Ugen64","Ulayiti","Uncle G",
"Utcursch","Vague Rant","Vaoverland","Voice of All(MTG)","Waltpohl","Wayward","Who","Wiglaf","Wikiacc","Wikibofh",
"WikiFanatic","Wilfried Derksen","Willmcw","Worldtraveller","Wwoods","Xezbeth","Y0u","Yelyos","Zocky","Zscout370",
"Zzyzx11","√Üvar Arnfj√∂r√∞ Bjarmason","–Ç–æ—Ä—í–µ –î. –ë–æ–∂–æ–≤–∏—õ","80-MAN","ABCD.09","Activision45","Admiral Roo","AfC","Agent003","AlbertR",
"Appleboy","ari89","Aytakin","B-101","Bancroftian","Beau99","Ben Arnold","Bkwillwm","Bluejean","bob rulz",
"Bobblewik","Boothy443","Bourbons3","BrandonYusufToropov","BugzPal","Bushytails","Canaen","Casito","Chamaeleon","Chanting Fox",
"Chanting Fox (2nd)","Chooserr","Chowells","CJS102793","Coburnpharr04","Cognition","Comics","Darrien","Davetunney","Dinopup",
"Doidimais Brasil","DrZoidberg","E. Brown","EddieSegoura","EdwinHJ (renomination)","Eequor (2nd)","EinsteinMC2","Empty2005","EventHorizon","Falcon Kirtaran.10",
"Firebug","FuriousFreddy r1","Garykirk","Gkhan","Goeagles4321","Halibutt","Hollow Wilerding","Howabout1","Imaglang","Instantnood",
"Jobe6","\"Just zis Guy, you know?\"","Kappa","Kils","Kmweber","KuatofKDY","Litefantastic","Lst27","Minghong","Misterrick",
"Monkbel","Mrmattkatt","mtmdem","Musachachado","NickBush24","Niz","NSR","One Salient Oversight","Pavel Vozenilek","Pedant",
"Peter Ellis","Poccil2","Poiuytman","Private Butcher","psufan2007","Purplefeltangel","Purplefeltangel2","Pyrop","Quale","Rainbowwarrior1977",
"Rfc1394","Richard Arthur Norton (1958- )","Rl","salvag","Sam Vimes","SamuraiClinton","Scott Gall","ScottyBoy900Q","Shaddack","Sherurcij",
"Spinboy","Spottedowl","SqueakBox","Stevey7788","Susvolans","Tedernst","Thelb4","ThomasK","Tony1","V. Molotov",
"Vikreykja","Wackymacs","Walter","WB","Wereon","Weyes","Weyes2","Weyes2a","WhatWouldEmperorNortonDo","WikiFan04",
"Wikiwoohoo2","Wonderfool","YHoshua","Zappaz","Zereshk","Zxcvbnm","Academic Challenger","AlainV","Alex S","AllyUnion",
"ALoan","Ambivalenthysteria","Andrevan","Andrew Yong","Andrewa","Andris","AndyL","Aranel","Aris Katsaris","Arminius",
"Arvindn","Bearcat","Benc","Bkonrad","Blankfaze","Bmills","Brockert","Caltrop","Catbar","CatherineMunro",
"Cecropia","Chancemill","Charles Matthews","Chmod007","Chris Roy","ChrisO","Chuq","CJCurrie","COGDEN","ContiE",
"Cool Hand Luke","CryptoDerk","CSTAR","Cutler","CyborgTosser","Cyrius","Dale Arnett","DanKeshet","David.Monniaux","David Gerard",
"David Newton","Davidcannon","DavidWBrooks","Davodd","Dbachmann","Dcoetzee","Decumanus","Derek Ross","DF08","Diberri",
"Dino","DJ Clayworth","Dmn","Dpbsmith","DropDeadGorgias","Duk","Duncharris","Dwindrim","Earl Andrew","Ed g2s",
"Elf","Exploding Boy","Ezhiki","Fabiform","Fennec","Ferkelparade","Ffirehorse","Fire Star","Flockmeal","Francs2000",
"Frazzydee","Fredrik","Gadfium","Gamaliel","Gaz","GeneralPatton","Gentgeen","Geogre","Gerald Farinas","Golbez",
"Grunt","Gtrmp","Gwalla","Hadal","Hajor","Hawstom","Hcheney","Hemanshu","Hyacinth","Hypernovean",
"Ike9898","Imran","Isomorphic","Jallan","Jamesday","Jay","Jayjg","JCarriker","Jengod","Jeronimo",
"Jerzy","Jfdwolff","Jmabel","Johnleemk","JonMoore","Joy Stovall","Jpgordon","Jrdioko","Kaihsu","Karada",
"Kate","KF","Kim Bruning","KRS","Lachatdelarue","Lexor","Lord Emsworth","LouI","Lowellian","Ludraman",
"Lupo","MacGyverMagic","Mackensen","Mackeriv","Malcolm Farmer","Mark","Mark Richards","Markalexander100","Matt Crypto","Maury Markowitz",
"Maximus Rex","Merovingian","Mic","Michael Snow","Mikkalai","Mirv","Mkmcconn","Mkweise","Moink","Moncrief",
"Morven","Mustafaa","MykReeve","Neutrality","Nichalp","Niteowlneils","Nohat","Noldoaran","Nunh-huh","Oberiko",
"OldakQuill","Optim","Ortolan88","PedanticallySpeaking","PFHLai","Pfortuny","PMelvilleAustin","Pollinator","Premeditated Chaos","Proteus",
"PZFUN","Quadell","RadicalBender","Ran","Rbrwr","Rdsmith4","RedWolf","RedWordSmith","Rfl","Rhobite",
"Rhymeless","Rlandmann","Rmhermen","Roadrunner","Robin Patterson","RobLa","Roozbeh","Rossami","Salsa Shark","SD6-Agent",
"Seglea","Seth Ilys","Sewing","Shallot","Siroxo","Sj","Slowking Man","Snowspinner","Solipsist","Spencer195",
"Ssd","Stewartadcock","Stormie","Sverdrup","SWAdair","Taxman","Texture","TheCustomOfLife","Thue","Tillwe",
"Tim Ivorson","Timc","Tkinias","Tom-","Topbanana","UninvitedCompany","Urhixidur","UtherSRG","VampWillow","Violetriga",
"Visorstuff","Wapcaplet","Warofdreams","Wernher","Wesley","Wile E. Heresiarch","Woggly","Ww","XJamRastafire","Yacht",
"Zero0000","Zoicon 5","Zoney","AdamRetchless.09","An√°rion","An√°rion2","Anthony DiPierro","BRG","Calmypal.09","Chan Han Xiang",
"Chocolateboy.09","ChrisDJackson.09","Colipon.09","DCEdwards1966","EDGE","Eequor","Falcon Kirtaran.09","IndigoGenius","Indrian","Itai.09",
"Leonard G.","LGagnon","Lst27.09","Lucky 6.9.08","Lucky 6.9 round 2","Markalexander100.09","Maurreen","Misterrick.09","Nathanlarson32767","Netoholic",
"Nikola Smolenski","Norm","P3d0","Plato.07","Plato.08","Poccil","Pumpie","Rei.09","Rogper.09","ScudLee",
"ShaneKing","Skyler1534","Squash","TakuyaMurata","Taoster","TheCustomOfLife.09","WHEELER.09","168...","Ahoerstemeier","Andres",
"Ark30inf","Arwel Parry","Bcorr","Christopher Mahan","Daniel Quinlan","DavidLevinson","Dieter Simon","Dysprosia","Efghij","Evil saltine",
"Finlay McWalter","Fuzheado","Ihcoyc","Jlk73","Jwrosenzweig","Khym Chanur","Llywrch","Marshman","Michael Hardy","Morwen",
"Muriel Gottrop","Nanobug","Pakaran","Paul A","Pcb21","Pratyeka","Secretlondon","SimonP","Snoyes","Stan Shebs",
"Sugarfish","Timwi","Tristanb","Vancouverguy","WhisperToMe"),
                        selected = "BDD"),
sliderInput("StartDate",
            "Start Date:",
            min = as.Date("08/16/03","%m/%d/%y"),
            max = as.Date("06/05/13","%m/%d/%y"),
            value=as.Date("06/05/07"),timeFormat="%m/%d/%y"),
sliderInput("EndDate",
            "End Date:",
            min = as.Date("08/16/03","%m/%d/%y "),
            max = as.Date("06/05/13","%m/%d/%y"),
            value=as.Date("06/05/07"),timeFormat="%m/%d/%y"),
sliderInput('vSize', UIcharSet$vSize, min=.5, max=5.5,
            value=2, step=.1, round=0),
sliderInput('eLWD', UIcharSet$eLWD, min=0.1, max=2,
            value=1.5, step=0.1, round=0),
selectInput('vfcolor', UIcharSet$vfcolor, colorSet,selected="black")

        ),

        # Show a plot of the generated distribution
        mainPanel(
            plotOutput("distPlot", width=800, height=800)
        )
    )
))
